# SPDX-License-Identifier: Apache-2.0
#
# Copyright (C) 2025 LRSTS <lrsts@qq.com>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Luci Cloudflare DDNS Automatic Updater Web Interface
LUCI_DEPENDS:=+cfddns-updater
PKG_VERSION:=1.0.1
PKG_RELEASE:=2
PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=LRSTS <lrsts@qq.com>

include ../../luci.mk
# call BuildPackage - OpenWrt buildroot signature
